info:
  description: WFD Menu Samples
  url: https://github.com/dbellagio/wfd-menu-config
eureka:
  client:
    serviceUrl:
      # defaultZone: http://172.17.0.2:8761/eureka
      defaultZone: http://172.31.0.131:8761/eureka

